Abir epic 7.1 imp
AaronSosaRamos/kai-ai-backend pull request #11
Opened 2024-09-30 16:25 UTC by asleem

1- created 2 method for audio transcript
2- created 4 tests for the above methods
3- added file_type check for the file_url

2024-10-01 16:09 UTC, AaronSosaRamos requested changes
Please, check the comment and send a screenshot of the Unit Tests that have passed appropriately.

2024-10-01 16:09 UTC, AaronSosaRamos commented on .vscode/settings.json
This file is not needed. Please, remove it.

2024-10-02 15:52 UTC, asleem commented on .vscode/settings.json
DONE

2024-10-02 15:53 UTC, asleem commented on .vscode/settings.json
![Screenshot 2024-10-02 at 11 48 45 AM](https://github.com/user-attachments/assets/4334419f-f059-418d-beaf-487fc5564c13)

2024-10-09 16:02 UTC, AaronSosaRamos approved these changes
LGTM

2024-10-09 16:02 UTC, merged